
version: '3.1'
services:
  app:
    container_name: nosql-injection-sequelize
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - '8000:3000'
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  
